##设置数据库连接池
spring:
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    ## 启用热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错 java.lang.ClassNotFoundException:
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
## 端口号  上下文路径
server:
  port: 8080
  servlet:
    context-path: /crm
##mybatis配置
mybatis:
  type-aliases-package: com.yjxxt.crm.bean;com.yjxxt.crm.query;com.yjxxt.crm.dto
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
##日志
logging:
  level:
    com:
      yjx:
        crm:
          mappers: debug
## pageHelper 分页
pagehelper:
  helper-dialect: mysql
